#!/bin/bash
# General Aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Movement
alias ll="ls -lh"
alias la="ls -al"
alias gohome="cd ~;clear;"

# Git
alias pullall="find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;"
alias checkall="find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} status \;"
alias gitupdate='git add --all; git commit -am "update"; git push'
alias fixgitignore='git rm --cached `git ls-files -i --exclude-from=.gitignore`'
alias gaa='git add --all'
alias gst='git status'
alias gbpurge="git checkout master; git pull origin master; git fetch --all -p; git branch -vv | awk '$3 $4 ~ /:gone]$/ { print $1 }' | xargs -n 1 git branch -d"
alias fixssh='eval "$(ssh-agent -s)";ssh-add'

# The following are handled in .zprezto/modules/git/alias.zsh
# alias gia='git add'
# alias gcm='git commit -m'
# alias gcam='git commit -am'
# alias gfm='git pull'
# alias gfr='git pull --rebase'
# alias gp='git push'

# General
alias updateall="sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove -y && sudo apt autoclean -y"

